### ISSUE TITLE
Plot breaks if there is 'Inf' in the CI

### ISSUE THREAD

**Issue by andreasleha** [NikNakk/forestmodel#13]
The plot completely breaks if there is an `Inf` in the CI somewhere.  While generating a plot is hard here, the tables should still be generated.

Example:

      library("forestmodel")
      library("survival")
      library("dplyr")
      pretty_lung <- lung %>%
        transmute(time,
                  status,
                  Age = age,
                  Sex = factor(sex, labels = c("Male", "Female")),
                  ECOG = factor(lung$ph.ecog),
                  `Meal Cal` = meal.cal) %>%
         mutate(time = ifelse(ECOG == 3, 30000, time))
      
      print(forest_model(coxph(Surv(time, status) ~ ., pretty_lung)))

**Comment by NikNakk** [comment]
Sorry for the delayed response. I've now put a fix into the latest development version on github.
