### ISSUE TITLE
Plotting without intercept

### ISSUE THREAD

**Issue by NikNakk** [NikNakk/forestmodel#14]
I'm finding its package for the representation of the coefficients very useful. I use it often because I consider it the most advanced. 

But I did not find a way to remove the intercept from the forest model plot. Do you have any suggestions? 
I use this code: print(forest_model(mod)) with library(forestmodel).

**Comment by NikNakk** [comment]
Fixed in 0.5.1

**Comment by gabrakadabra** [comment]
Will there be a release for 0.5.1? This feature would be very appreciated.
