### ISSUE TITLE
Covariates argument doesn't behave as described

### ISSUE THREAD

**Issue by alisoncallahan** [NikNakk/forestmodel#15]
Specifying covariates to include in the plot changes the order that covariates are displayed, and how they are displayed, but does not filter to just those variables.

Example:

```
library("survival")
library("dplyr")
pretty_lung <- lung %>%
  transmute(time,
            status,
            Age = age,
            Sex = factor(sex, labels = c("Male", "Female")),
            ECOG = factor(lung$ph.ecog),
            `Meal Cal` = meal.cal)
print(forest_model(coxph(Surv(time, status) ~ ., pretty_lung), covariates = c("ECOG")))
```

**Comment by NikNakk** [comment]
This should have been fixed a while ago in the latest version on github. I've been slow at pushing it to CRAN. Could you please check when you have time? Install using `remotes::install_github("NikNakk/forestmodel")`

**Comment by alisoncallahan** [comment]
That did it! Works as documented. Thanks for the quick reply!!
