### ISSUE TITLE
How to set limits and ticks

### ISSUE THREAD

**Issue by ShixiangWang** [NikNakk/forestmodel#16]
Dear author,

When I set the limits, I find the plot is incorrect.

![image](https://user-images.githubusercontent.com/25057508/62532626-65337180-b877-11e9-9b43-437491825514.png)

And I want to know how to set custom ticks.

Best,
Shixiang

**Comment by NikNakk** [comment]
Is your issue regarding the error bars overlapping, or the numbers for the
limits not corresponding to what's shown? If it's the latter, make sure you
log transform the limits (i.e. limits = log(c(lim1, lim2))). If the former,
the plot is constructed as a ggplot2 plot that includes all of the panels.
As such, it's more difficult to truncate the error bars used for the
confidence intervals. I could in theory implement this by overplotting
rectangles in front of the panes that don't contain the forest plot, or by
truncating the error bars at the ends and plotting them without the tick at
the end, but either would take some time which I don't currently have.

Regarding the ticks, how did you want to make them different?

BW

Nick

**Comment by ShixiangWang** [comment]
Please see https://github.com/NikNakk/forestmodel/pull/17.

I read your source code and think it is really amazing that you implemented forest plot using `ggplot2` instead of `grid` or something else I thought. Great work! 👍 

Best,
Shixiang
