### ISSUE TITLE
A warning message from changing the text_size

### ISSUE THREAD

**Issue by yuemolin** [NikNakk/forestmodel#22]
Hi NikNakk, 
Thank you for your wonderful package!

A Warning message showed up when I trying to modify the text_size in format_options:
```{r}
'Warning: Ignoring unknown aesthetics: x'
```
I'm not sure am I doing something wrong? I'm hoping you can help me with this, thanks!
Here, I attached my code:
```{r}
forest_model(model1,factor_separate_line = T,
             format_options = list(colour= "black", shape = 15, text_size = 20,fontsize=5, banded = T),
             theme = theme_forest())
```

BTW, I'm also wondering is there a way to modify the size of the point estimates?

**Comment by ShixiangWang** [comment]
Could you show your full comands with a minimal dataset?

**Comment by yuemolin** [comment]
My code is as below:
```{r}
Cox.ppi = coxph(Surv(N, O) ~ A+B+C+D+E+G+H+I+J+K+L,
                weights = M, data = data)

library("forestmodel")
forest_model(Cox.ppi,factor_separate_line = T,
             format_options = list(colour= "black", shape = 15, text_size = 10, banded = T),
             theme = theme_forest())
```
And the data is attached.
Thanks!
[test.txt](https://github.com/NikNakk/forestmodel/files/4602633/test.txt)

**Comment by ShixiangWang** [comment]
@yuemolin  Please try:


```r
data = read.csv("~/Downloads/test.txt")
library(survival)

Cox.ppi = coxph(Surv(N, O) ~ A+B+C+D+E+G+H+I+J+K+L,
                weights = M, data = data)

#library("forestmodel")
forest_model(Cox.ppi,
             format_options = forest_model_format_options(text_size = 3))

```

**Comment by yuemolin** [comment]
got it! Thank you so much

**Comment by ShixiangWang** [comment]
You are welcome, please close this issue if you have no further problem
