### ISSUE TITLE
Forest Plot not generated for a single predictor

### ISSUE THREAD

**Issue by drsantam** [NikNakk/forestmodel#5]
We cannot generate a forest plot for a single predictor. It shows an error "Unkown Coloumn".

**Comment by NikNakk** [comment]
Could you give me some example data/code?

 

BW

 

Nick

**Comment by vjd** [comment]
Function fails to work with single predictor. here is an example code from your `readme`

```
os <- lung %>%
  transmute(time,
            status,
            Age = age,
            Sex = factor(sex, labels = c("Male", "Female")),
            ECOG = factor(lung$ph.ecog),
            `Meal Cal` = meal.cal)

print(forest_model(coxph(Surv(time, status) ~ Sex, os)))
```

**Comment by NikNakk** [comment]
Thanks for your feedback. Could you try the updated version to check it fixes it? `devtools::install_github("NikNakk/forestmodel/fix_coxph_one")`

**Comment by vjd** [comment]
this fix works. Thanks. just to clarify, the devtools install in the previous comment requires and `@`

`devtools::install_github("NikNakk/forestmodel@fix_coxph_one")`

**Comment by NikNakk** [comment]
Yes, apologies. I'll pull the changes into master and resubmit to CRAN at some stage.
