### ISSUE TITLE
Labels 

### ISSUE THREAD

**Issue by gajyakichi** [NikNakk/forestmodel#7]
Thank you for your great package. 
I have two questions.

1)Can the labels for factors in the panel be changed?
2)Is it available the model that has interaction such as 

> CoxModelFull<- coxph(Surv(FU, Censor==1)~(Factor1+Facgtor2)^2, data, method="breslow")

**Comment by NikNakk** [comment]
Thanks for your interest.

 

1.	No, but this can be done by manipulating the data prior to model generation i.e. data$variable <- factor(data$variable, levels = c(<existing levels>), labels = c(<new labels in same order as existing ones>))
2.	At the moment, there’s no support for interacting terms. It could theoretically be done, but it would be quite a bit of work and I don’t have the time at present.

 

Best wishes,

 

Nick
